### ISSUE TITLE
Search no longer works.

### ISSUE THREAD

**Issue by Chnkr** [Konloch/bytecode-viewer#102]
Trying to use the search function on @samczsun his downstream fork results in a few interesting errors.

![](http://i.imgur.com/DWXS4pd.png)

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 1
        at the.bytecode.club.bytecodeviewer.gui.SearchingPane$4.valueChanged(SearchingPane.java:214)
        at javax.swing.JTree.fireValueChanged(JTree.java:2927)
        at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3391)
        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
        at javax.swing.JTree.setSelectionPath(JTree.java:1634)
        at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3548)
        at java.awt.Component.processMouseEvent(Component.java:6532)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Additionally, the regex search option also seems to be broken.

```
Exception in thread "Thread-11" java.lang.IllegalArgumentException: 0
        at the.bytecode.club.bytecodeviewer.searching.RegexInsnFinder.refresh(RegexInsnFinder.java:296)
        at the.bytecode.club.bytecodeviewer.searching.RegexInsnFinder.setMethod(RegexInsnFinder.java:305)
        at the.bytecode.club.bytecodeviewer.searching.RegexInsnFinder.<init>(RegexInsnFinder.java:214)
        at the.bytecode.club.bytecodeviewer.searching.RegexSearch.search(RegexSearch.java:68)
        at the.bytecode.club.bytecodeviewer.gui.SearchingPane$3$2.doSearch(SearchingPane.java:172)
        at the.bytecode.club.bytecodeviewer.searching.BackgroundSearchThread.run(BackgroundSearchThread.java:47)
```

**Comment by Konloch** [comment]
Thanks for the report! If I get some free time I'll take a look into this.
