### ISSUE TITLE
v3.0.0-preview1 hangs on start (OS X)

### ISSUE THREAD

**Issue by zxcat** [Konloch/bytecode-viewer#107]
console shows:

```
https://the.bytecode.club - Created by @Konloch and @samczsun - Bytecode Viewer 3.0.0
Checking libraries
Checking Enjarify
Moving Enjarify
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at org.zeroturnaround.zip.ZipUtil.<clinit>(ZipUtil.java:70)
    at the.bytecode.club.bytecodeviewer.Boot.checkEnjarify(Boot.java:101)
    at the.bytecode.club.bytecodeviewer.Boot.boot(Boot.java:61)
    at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:187)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 4 more
```

OSX 10.10.5,

```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

v2.9.8-fatjar works fine.

**Comment by Konloch** [comment]
May have been something I missed during export. Or possibly a library I didn't add.

I'll fix this once I have some free time, thanks for the report!

**Comment by schniggie** [comment]
Same here on Windows 7 64bit

>java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
