### ISSUE TITLE
Krakatau invocation fails on windows if username contains a space.

### ISSUE THREAD

**Issue by p0lm** [Konloch/bytecode-viewer#109]
Because Bytecode-viewer uses a temporary folder created in `$USER/.Bytecode/bcv_temp` for keeping the .java sources, invocation of Krakatau on Windows fails if `$USER` contains a space.

```
Process:



Error:


  File "C:\Users\USER WITH SPACE\.Bytecode-Viewer\krakatau_8\Krakatau-master\decompile.py", line 87
    print 'processing target {}, {} remaining'.format(target.encode('utf8'), len(targets)-i)
         ^
SyntaxError: invalid syntax

Exit Value is 1
Bytecode Viewer Version: 2.9.8

java.io.FileNotFoundException: C:\Users\USER WITH SPACE\.Bytecode-Viewer\bcv_temp\UxOpxabqRdbvzwHIAyMfHEgrOKYijrrx\q\nx.java (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:63)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDecompiler.decompileClassNode(KrakatauDecompiler.java:106)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$15.doShit(ClassViewer.java:1277)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)
```

This can be resolved by properly escaping the $USER path before invoking krakatau, or wrapping it in `"(...)"`. Another, maybe more preferable option, but a little more work, would be providing an option for specifiying the `temp` folder.

**Comment by Konloch** [comment]
Cheers, I'll be sure to implement this when I've got free time.

**Comment by samczsun** [comment]
I don't think it's the user with space causing it. You appear to be using Python 3

**Comment by afffsdd** [comment]
no, this is because you are using Python 3, where print is an actual function not a statement

**Comment by Konloch** [comment]
closing
