### ISSUE TITLE
ArrayIndexOutOfBoundsException and NullPointerException on specific APK

### ISSUE THREAD

**Issue by intruder777** [Konloch/bytecode-viewer#141]
Latest release version 2.9.8 crashes upon opening this APK: 
https://mega.nz/#!khkETDoL!1TU35Uf5oSxBIC9m_0koswqVxnU5ZbLlgDGbR3MAGCQ

Bytecode Viewer throws two exceptions:

```
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
    at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:867)
```

and

```
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.ArrayIndexOutOfBoundsException: 7
    at brut.a.b.b.a.b(Unknown Source)
    at brut.a.b.b.a.a(Unknown Source)
    at brut.a.b.a.a(Unknown Source)
    at brut.a.b.a.a(Unknown Source)
    at brut.a.a.a(Unknown Source)
    at brut.a.c.a(Unknown Source)
    at brut.apktool.Main.main(Unknown Source)
    at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
    at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:863)
```

The APK is obfuscated, so maybe this is the reason. But anyway Bytecode Viewer should have handle such APKs. Please have a look.

**Comment by henriquedesousa** [comment]
Mine is similar: 

```
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:868)
```
and

```
brut.a.a.e: resource spec: 0x010104e2
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.r.a(Unknown Source)
	at brut.a.b.a.a.s.h(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:864)
```

**Comment by Konloch** [comment]
Thank you for the reports and the example APK! I've confirmed this issue is fixed in the latest version of BCV.
