### ISSUE TITLE
ArrayIndexOutOfBoundsException at jd.cli.util.ClassFileUtil.ExtractDirectoryPath

### ISSUE THREAD

**Issue by lu-ko** [Konloch/bytecode-viewer#158]
JD-GUI error! Send the stacktrace to Konloch at http://the.bytecode.club or konloch@gmail.com

Suggested Fix: Click refresh class, if it fails again try another decompiler.

Bytecode Viewer Version: 2.9.8

```
java.lang.ArrayIndexOutOfBoundsException: 28944
	at jd.cli.util.ClassFileUtil.ExtractDirectoryPath(ClassFileUtil.java:48)
	at the.bytecode.club.bytecodeviewer.decompilers.JDGUIDecompiler.decompileClassNode(JDGUIDecompiler.java:63)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$13.doShit(ClassViewer.java:834)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)
```

**Comment by jowasp** [comment]
could you repeat the steps to reproduce the error? (pls include also on which OS you are using)

**Comment by lu-ko** [comment]
You can reproduce the error when you try to decompile .class file that contains Java 8 Lambda Expression using JD-GUI decompiler. Sample class:

```
package com.example;

import java.util.Arrays;
import java.util.List;

public class TestClass {

	public void doSomething() {
		List<String> list = Arrays.asList("a", "b", "c", "d");
		list.forEach(element -> {
			System.out.println(element);
		});
	}
}
```

Error disappears if you remove lambda expression, e.g.:
```
package com.example;

import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;

public class TestClass {

	public void doSomething() {
		List<String> list = Arrays.asList("a", "b", "c", "d");
		list.forEach(new TestConsumer());
	}

	private class TestConsumer implements Consumer {

		@Override
		public void accept(Object element) {
			System.out.println(element);
		}
	}
}
```

My environment:

- Java(TM) SE Runtime Environment (build 1.8.0_111-b14), 64-bit
- Windows 10 (Home) build 14393, 64-bit
