### ISSUE TITLE
Cannot open apk over windows platform

### ISSUE THREAD

**Issue by leiwen83** [Konloch/bytecode-viewer#159]
I am using the 2.9.8 release, and cannot open any apk file.
while for jar file, it is ok.

**Comment by jowasp** [comment]
You cannot open it or just don't get decompiled?

**Comment by firstlevelIT** [comment]
the error is 
java.io.FileNotFoundException: C:\Users\stefano\.Bytecode-Viewer\bcv_temp\kDmsdgeGaOCTfcdODOZyVmypc.jar (Impossibile trovare il file specificato)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at the.bytecode.club.bytecodeviewer.JarUtils.loadClasses(JarUtils.java:83)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:877)

**Comment by legit** [comment]
Same problem over here.

**Comment by JoeryDroppers** [comment]
Same

**Comment by Konloch** [comment]
This should be fixed in the latest version, thank you for the reports!
