### ISSUE TITLE
A couple of exceptions when decompiling an APK

### ISSUE THREAD

**Issue by norey** [Konloch/bytecode-viewer#162]
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
    at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:867)

and

Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

brut.a.a.e: resource spec: 0x010104e2
    at brut.a.b.a.d.b(Unknown Source)
    at c.c.a.a.b.d.a(Unknown Source)
    at c.c.a.a.b.d.a(Unknown Source)
    at brut.a.b.a.a.r.d(Unknown Source)
    at brut.a.b.a.a.r.a(Unknown Source)
    at brut.a.b.a.a.s.h(Unknown Source)
    at brut.a.b.a.a.u.a(Unknown Source)
    at brut.a.b.a.c(Unknown Source)
    at brut.a.a.b(Unknown Source)
    at brut.a.c.a(Unknown Source)
    at brut.apktool.Main.main(Unknown Source)
    at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
    at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:863)

Currently on

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
Windows 10

**Comment by unascribed** [comment]
Workaround: Disable "Decode APK Resources".

**Comment by doridori** [comment]
think APKTool needs a bump to 2.3.0 as see a similar issue when using the 2.2 version in standalone
