### ISSUE TITLE
java.lang.NullPointerException at BytecodeViewer.java:867

### ISSUE THREAD

**Issue by MariusBordeian** [Konloch/bytecode-viewer#166]
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:867)

-------------------

Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

brut.a.a.e: resource spec: 0x010104e2
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.r.a(Unknown Source)
	at brut.a.b.a.a.s.h(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:863)

**Comment by MariusBordeian** [comment]
while trying to open "com.google.android.wearable.app_2.0.0.147108189.gms-770039114_minAPI18(nodpi)_apkmirror.com.apk".

**Comment by Konloch** [comment]
This should be fixed in the latest version of BCV, thanks for the report!
