### ISSUE TITLE
 java.lang.NullPointerException in BytecodeViewer.java:868 and brut.a.a.e: resource spec: 0x010104e2

### ISSUE THREAD

**Issue by utamir** [Konloch/bytecode-viewer#167]
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:868)

----------

Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

brut.a.a.e: resource spec: 0x010104e2
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.r.a(Unknown Source)
	at brut.a.b.a.a.s.h(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:864)

**Comment by danfiscus** [comment]
I also received this error message while trying to decompile [Betternet](https://play.google.com/store/apps/details?id=com.freevpnintouch)

**Comment by funtax** [comment]
Some for me, decompiling DoubleTwist:
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

brut.a.a.e: resource spec: 0x010104e0
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:863)

**Comment by austinheap** [comment]
Same here 😞

**Comment by yujiaao** [comment]
When I decode [this apk](http://weixin.qq.com/r/OEzUzGjEzTWyrSyv9xkq), I got the same error

`I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
brut.a.a.e: resource spec: 0x010104e2
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.r.a(Unknown Source)
	at brut.a.b.a.a.s.h(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:864)
java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:868)
`

**Comment by doridori** [comment]
think APKTool needs a bump to 2.3.0 as see a similar issue when using the 2.2 version in standalone

**Comment by Mohanad-k** [comment]
I received the same error :
brut.a.a.e: resource spec: 0x010104e2
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.r.a(Unknown Source)
	at brut.a.b.a.a.s.h(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:864)
java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:868)

I resolved it by disabling Decode APK Resources from the Settings menu which is enabled by default.

Hope this will help.

**Comment by bizzareshishir** [comment]
@Mohanad-k , disabling Decode APK Resources from the Settings menu works. Thanks.

**Comment by Konloch** [comment]
Should be fixed in the latest version, if it's not please E-Mail me or create a new issue.
