### ISSUE TITLE
Error trying to use Krakatau Decompiler in Bytecode Viewer fatjar version.

### ISSUE THREAD

**Issue by gakar06** [Konloch/bytecode-viewer#170]
I'm using "BytecodeViewer 2.9.8-fatjar.jar" and when I try to use the Krakatau decompiler I get the following error.  Does anyone know how to fix this?

Error:

C:\Python27\python.exe: can't open file '\decompile.py': [Errno 2] No such file or directory

Exit Value is 2
Bytecode Viewer Version: 2.9.8

java.io.FileNotFoundException: C:\Users\<USERNAM>\.Bytecode-Viewer\bcv_temp\aZwHbaOWaEIOHcehIDJEcTyBVgsUPMUr\<FILENAME> (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:63)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDecompiler.decompileClassNode(KrakatauDecompiler.java:106)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$13.doShit(ClassViewer.java:774)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)

**Comment by ItzSomebody** [comment]
Try deleting the folder C:\Users<USERNAM>.Bytecode-Viewer\bcv_temp

**Comment by gakar06** [comment]
Deleting that folder didn't work.  I get the same error still.  The folder "aZwHbaOWaEIOHcehIDJEcTyBVgsUPMUr" is empty though and doesn't contain the class file trying to be viewed.

**Comment by Storyyeller** [comment]
What happens if you run Krakatau directly? I suspect that BCV is failing to detect the correct location of Krakatau's output.

**Comment by gakar06** [comment]
Krakatau works fine if I run it directly outside of BCV. I just wanted to use it as a decompiler option in BCV.

**Comment by Konloch** [comment]
This should be fixed in v2.9.16, if it's not please open up a new issue. Thank you for the report!
