### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by jaspergould** [Konloch/bytecode-viewer#173]
Error compiling class: com/pnfsoftware/jeb/rcpclient/Assets

Keep in mind most decompilers cannot produce compilable classes

java.lang.Exception: 

Error:

C:\Users\WORK\.Bytecode-Viewer\bcv_temp\tempRgGPupmpPpcC\com\pnfsoftware\jeb\rcpclient\Assets.java:4: error: package com.pnfsoftware.jeb.util.logging does not exist

    final private static com.pnfsoftware.jeb.util.logging.ILogger logger;

                                                         ^

C:\Users\WORK\.Bytecode-Viewer\bcv_temp\tempRgGPupmpPpcC\com\pnfsoftware\jeb\rcpclient\Assets.java:41: error: package com.pnfsoftware.jeb.util.logging does not exist

                    com.pnfsoftware.jeb.util.logging.ILogger a5 = logger;

                                                    ^

C:\Users\WORK\.Bytecode-Viewer\bcv_temp\tempRgGPupmpPpcC\com\pnfsoftware\jeb\rcpclient\Assets.java:53: error: package com.pnfsoftware.jeb.util.logging does not exist

        logger = com.pnfsoftware.jeb.util.logging.GlobalLog.getLogger(com.pnfsoftware.jeb.rcpclient.Assets.class);

                                                 ^

3 errors

Exit Value is 1

	at the.bytecode.club.bytecodeviewer.compilers.JavaCompiler.compile(JavaCompiler.java:96)

	at the.bytecode.club.bytecodeviewer.BytecodeViewer.compile(BytecodeViewer.java:740)

	at the.bytecode.club.bytecodeviewer.BytecodeViewer$10.run(BytecodeViewer.java:1227)

**Comment by jaspergould** [comment]
Error compiling class: com/pnf/plugin/oat/internal/OATFile

Keep in mind most decompilers cannot produce compilable classes



java.lang.Exception: 



Error:





C:\Users\WORK\.Bytecode-Viewer\bcv_temp\tempzIrGgFTPOKxH\com\pnf\plugin\oat\internal\OATFile.java:54: error: package com.pnfsoftware.jeb.util.logging does not exist

            com.pnfsoftware.jeb.util.logging.ILogger a1 = logger;

                                            ^

Note: C:\Users\WORK\.Bytecode-Viewer\bcv_temp\tempzIrGgFTPOKxH\com\pnf\plugin\oat\internal\OATFile.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

1 error



Exit Value is 1

	at the.bytecode.club.bytecodeviewer.compilers.JavaCompiler.compile(JavaCompiler.java:96)

	at the.bytecode.club.bytecodeviewer.BytecodeViewer.compile(BytecodeViewer.java:740)

	at the.bytecode.club.bytecodeviewer.BytecodeViewer$10.run(BytecodeViewer.java:1227)

**Comment by jaspergould** [comment]
Как я понял Krakatau не работает сейчас в режиме Java mode. Только в Bytecode.

Krakatau work with bytecode mode. And successful compiled.
