### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by 010100110111010001100101** [Konloch/bytecode-viewer#175]
Hi,

Just got this error:

Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.IllegalThreadStateException
	at java.lang.Thread.start(Thread.java:705)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.BOOT(BytecodeViewer.java:560)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:525)

Any ideas?

**Comment by savior14** [comment]
same issue

**Comment by Pilfer** [comment]
I'm also having this issue on OSX when I just run it with `java -jar bcv.jar`. It then throws an error saying Github is being slow. Huh.

**Comment by Konloch** [comment]
This should be fixed in v2.9.16, thank you for the reports!
