### ISSUE TITLE
Stacktraces when opening an APK

### ISSUE THREAD

**Issue by Vampire** [Konloch/bytecode-viewer#180]
I tried to open an APK and got

```
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

brut.a.a.e: resource spec: 0x010104e2
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.r.a(Unknown Source)
	at brut.a.b.a.a.s.h(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:863)
```

and

```
Bytecode Viewer Version: 2.9.8, Preview Copy: false, Fat Jar: false

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:867)
```

**Comment by paolog22** [comment]
same here

**Comment by paolog22** [comment]
any update on this ? cant do anything with this error
@Konloch sir i think this is critical .

**Comment by LukeOwncloud** [comment]
Same here. I tried to open the APK of the latest [Garmin connect](https://play.google.com/store/apps/details?id=com.garmin.android.apps.connectmobile&hl=en) version.

**Comment by Ghedeon** [comment]
Can confirm, same issue.

**Comment by korroktheslavemaster** [comment]
same issue. works fine with apktool

**Comment by Konloch** [comment]
Thanks for the reports guys! This should be fixed in the latest version. If it's not just create a new issue or E-Mail me directly.
