### ISSUE TITLE
can't open file '/disassemble.py

### ISSUE THREAD

**Issue by a247124718** [Konloch/bytecode-viewer#190]
why? please help me.
I have configured the python environment, but still error

/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/disassemble.py': [Errno 2] No such file or directory

Exit Value is 2
Bytecode Viewer Version: 2.9.8

java.io.FileNotFoundException: /Users/roy/.Bytecode-Viewer/bcv_temp/qprmTwYSTEJsGWWgKJVPaelBsNntxVfe/com/miui/zeus/b/a/b$a$a.j (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:62)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDisassembler.decompileClassNode(KrakatauDisassembler.java:87)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$15.doShit(ClassViewer.java:1306)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)

**Comment by galoti** [comment]
Same error with krakatau. I use krakatau in bytecode viewer for over 1 year and this error started last week.

**Comment by galoti** [comment]
Windows 10 and java version "1.8.0_161" here.

**Comment by a247124718** [comment]
@Konloch MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)    java version "1.8.0   
Thank you! My English is poor  , Now I have solved this problem by compiling the source code.
I guess This problem seems to be the first time to start without copy python file to the relevant directory

**Comment by Konloch** [comment]
Cheers, would you guys be able to check if the 2.9.10 release still has this bug? Thanks for the report!

**Comment by a247124718** [comment]
@Konloch  That's great. I've just tried it. He's been settled. At 2.9.10, thank you very much.

**Comment by Konloch** [comment]
Awesome, glad to hear that. Big thanks to @ItzSomebody for the patch.

**Comment by MaccariTA** [comment]
@Konloch The error reproduces in the newest version (2.9.11)
