### ISSUE TITLE
startup fail

### ISSUE THREAD

**Issue by tiann** [Konloch/bytecode-viewer#192]
java.awt.image.ImagingOpException: Unable to convolve src image
	at java.awt.image.ConvolveOp.filter(ConvolveOp.java:198)
	at sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:1108)
	at sun.java2d.pipe.ValidatePipe.transformImage(ValidatePipe.java:238)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3487)
	at com.apple.laf.AquaUtils$ShadowBorder.paintToImage(AquaUtils.java:331)
	at com.apple.laf.AquaUtils$ShadowBorder.paintBorder(AquaUtils.java:304)
	at com.apple.laf.AquaUtils$SlicedShadowBorder.<init>(AquaUtils.java:345)
	at com.apple.laf.AquaInternalFrameUI$4.getForegroundShadowBorder(AquaInternalFrameUI.java:708)
	at com.apple.laf.AquaInternalFrameUI$InternalFrameShadow.getInstance(AquaInternalFrameUI.java:765)
	at com.apple.laf.AquaInternalFrameUI$InternalFrameShadow.getInstance(AquaInternalFrameUI.java:760)
	at com.apple.laf.AquaUtils$RecyclableSingleton.lambda$get$0(AquaUtils.java:180)
	at sun.awt.AppContext.getSoftReferenceValue(AppContext.java:914)
	at com.apple.laf.AquaUtils$RecyclableSingleton.get(AquaUtils.java:180)
	at com.apple.laf.AquaInternalFrameUI.installUI(AquaInternalFrameUI.java:125)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JInternalFrame.setUI(JInternalFrame.java:388)
	at javax.swing.JInternalFrame.updateUI(JInternalFrame.java:404)
	at javax.swing.JInternalFrame.<init>(JInternalFrame.java:351)
	at the.bytecode.club.bytecodeviewer.gui.VisibleComponent.<init>(VisibleComponent.java:41)
	at the.bytecode.club.bytecodeviewer.gui.WorkPane.<init>(WorkPane.java:64)
	at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI.<init>(MainViewerGUI.java:443)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:509)

**Comment by Konloch** [comment]
Could you give me your operating system and java version? Also which BCV version are you running?

Cheers!

**Comment by tiann** [comment]
> uname -a
Darwin weishudeMacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64

> javac -version
javac 1.8.0_101

> ls Bytecode*
Bytecode-Viewer-2.9.10.jar

**Comment by Konloch** [comment]
Would you be able to see if this preview 2.9.11 copy will work?

[Bytecode-Viewer-2.9.11.jar.zip](https://github.com/Konloch/bytecode-viewer/files/1837139/Bytecode-Viewer-2.9.11.jar.zip)

I've emptied the buffered image array for all of the icons and I've set the icon to null, this should result in all the panes being loaded with the default Java icon
