### ISSUE TITLE
Every time i add apk to decompile show me this 2 Error dialogs (java.io.IOException, java.lang.NullPointerException)

### ISSUE THREAD

**Issue by EiderDiaz** [Konloch/bytecode-viewer#200]
# 1
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_16

java.io.IOException: Unable to delete file: C:\Users\eider\.Bytecode-Viewer\bcv_temp\Decoded Resources\res\values-v26\styles.xml
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:30)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:916)
# 2
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_161

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:920)

**Comment by Konloch** [comment]
This should be fixed in the latest version, thanks for this report!
