### ISSUE TITLE
Issue with krakatau and files

### ISSUE THREAD

**Issue by Daswf852** [Konloch/bytecode-viewer#202]
When opening a class with krakatau disassembler/decompiler the following error is given:  
```
Process:

Error:

/usr/bin/python2.7: can't open file '/disassemble.py': [Errno 2] No such file or directory

Exit Value is 2
Bytecode Viewer Version: 2.9.11

java.io.FileNotFoundException: /home/daswf852/.Bytecode-Viewer/bcv_temp/YmtsaHbxezjTsKCBgzbmoqPBZrBBytBu/net/direc/tory/file.j (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:62)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDisassembler.decompileClassNode(KrakatauDisassembler.java:104)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$14.doShit(ClassViewer.java:1236)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:33)
  ```  
  
the error is the same on terminal.  
OS: kubuntu 18.04, AMD64  
Java: java-8-openjdk-amd64

**Comment by john19922** [comment]
The error is possibly for a minor change in name of the file & path "Krakatau-master\disassemble.py", though the disassemble.py file is "Krakatau-master\assembler\disassembly.py"

Process:
Error:
C:\Python27\python.exe: can't open file 'C:\Users\.Bytecode-Viewer\krakatau_10\Krakatau-master\disassemble.py': [Errno 2] No such file or directory

Exit Value is 2
Bytecode Viewer Version: 2.9.11

java.io.FileNotFoundException: C:\Users\subha\.Bytecode-Viewer\bcv_temp\XyQpBAlhkCGCNTQQePuQbwDEsyCamPZe\ds\d.j (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at java.base/java.io.FileReader.<init>(FileReader.java:72)
	at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:62)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDisassembler.decompileClassNode(KrakatauDisassembler.java:104)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$14.doShit(ClassViewer.java:1236)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:33)

**Comment by Storyyeller** [comment]
`disassemble.py` is correct. `assembler\disassembly.py` is an internal file, not an entrypoint.

**Comment by GSharma789** [comment]
@Storyyeller i am also facing same issue on windows , python 2, 3 ,jdk,jre all are installed but krakatau decompiler not working although all other decompiler working fine . Using 2.9.11

**Comment by Storyyeller** [comment]
Unfortunately, I can't control how BCV tries to invoke Krakatau. You can either use Krakatau manually or weight for Konloch to fix BCV.

**Comment by Konloch** [comment]
Hi, sorry for the late reply! This should be fixed in the latest version, if it's not please let me know by opening a new issue.
