### ISSUE TITLE
I try to decompile a dex, but come across a NPE

### ISSUE THREAD

**Issue by TYZRPVX** [Konloch/bytecode-viewer#204]
I try to decompile a dex, but come across a NPE. Did I make a mistake in executing a command prompt?

It hints like this:

```
> java -jar Bytecode-Viewer-2.9.11.jar -i classes.dex -o out -t all
https://the.bytecode.club - Created by @Konloch - Bytecode Viewer 2.9.11, FatJar: true
Start up took 5 seconds
You can define another decompiler by appending -decompiler "name", by default procyon has been set.
Decompiling C:\Users\xxx\Downloads\classes.dex with Procyon
dex2jar C:\Users\xxx\Downloads\classes.dex -> classes-dex2jar.jar
java.lang.NullPointerException
        at the.bytecode.club.bootloader.Boot.populateLibsDirectory(Boot.java:327)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:408)
Finished.
Bytecode Viewer CLI v2.9.11 by @Konloch - http://bytecodeviewer.com
```

**Comment by Konloch** [comment]
This should be fixed in the latest version, if it's not please create a new issue on GitHub or E-Mail me directly. Cheers!
