### ISSUE TITLE
2.9.11 - file not found when opening local APK

### ISSUE THREAD

**Issue by voltagex** [Konloch/bytecode-viewer#210]
It looks like this is a problem converting APK to JAR with the latest BCV - some APKs throw this, some don't

```
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_161

java.io.FileNotFoundException: C:\Users\live\.Bytecode-Viewer\bcv_temp\OvjGjPVwhHmQaiknnbHxMbptM.jar (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at the.bytecode.club.bytecodeviewer.JarUtils.loadClasses(JarUtils.java:100)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:930)
```

[working.zip](https://github.com/Konloch/bytecode-viewer/files/2195601/working.zip)
[crashes.zip](https://github.com/Konloch/bytecode-viewer/files/2195602/crashes.zip)

**Comment by Konloch** [comment]
Thank you for including an example! Using it I've confirmed this has been patched in the latest version https://github.com/Konloch/bytecode-viewer/releases/tag/v2.9.15
