### ISSUE TITLE
failed to decompile minecraft1.13.jar file a.class

### ISSUE THREAD

**Issue by uuk0** [Konloch/bytecode-viewer#211]
JD-GUI error! Send the stacktrace to Konloch at http://the.bytecode.club or konloch@gmail.com

Suggested Fix: Click refresh class, if it fails again try another decompiler.

Bytecode Viewer Version: 2.9.11

java.lang.ArrayIndexOutOfBoundsException: 21008
	at jd.cli.util.ClassFileUtil.ExtractDirectoryPath(ClassFileUtil.java:48)
	at the.bytecode.club.bytecodeviewer.decompilers.JDGUIDecompiler.decompileClassNode(JDGUIDecompiler.java:80)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$13.doShit(ClassViewer.java:934)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:33)

**Comment by nanuaniua** [comment]
https://multi-win.000webhostapp.com/loonea-gagnez-de-largent/

2018-07-20 2:00 GMT-10:00 uuk0 <notifications@github.com>:

**Comment by jredfox** [comment]
it says that but, decompile it using fernflower and it works

**Comment by Konloch** [comment]
This should be fixed in v2.9.16, the default decompiler is now fernflower.
