### ISSUE TITLE
IllegalArgumentException in Objectweb

### ISSUE THREAD

**Issue by hheg** [Konloch/bytecode-viewer#214]
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at the.bytecode.club.bytecodeviewer.JarUtils.getNode(JarUtils.java:195)
	at the.bytecode.club.bytecodeviewer.JarUtils.put(JarUtils.java:75)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:882)

This seems to mainly happen when there are classes in X.jar/BOOT-INF/classes/ (spring boot jar/java10 source). That error is most likely related to a JDK 10 bug in ObjectAsm. The lib needed to fix this is 
```
             <dependency>
                            <groupId>org.ow2.asm</groupId>
                            <artifactId>asm</artifactId>
                            <version>6.1.1</version>
              </dependency>
```

**Comment by maxgerhardt** [comment]
Still not fixed in the latest release, attempting to open class files compiled with JDK10 and above failes. 

```
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 11.0.2

java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at the.bytecode.club.bytecodeviewer.JarUtils.getNode(JarUtils.java:195)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:896)
```

**Comment by Konloch** [comment]
This should be fixed in https://github.com/Konloch/bytecode-viewer/releases/tag/v2.9.13

Please let me know if you're still experiencing this issue.
