### ISSUE TITLE
Exception while trying to add APK

### ISSUE THREAD

**Issue by MohMah** [Konloch/bytecode-viewer#215]
I get these two exceptions when trying to decompile and APK:
```
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_101

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:920)

```

```
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_101

brut.a.a.e: resource spec: 0x010104e0
	at brut.a.b.a.d.b(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at c.c.a.a.b.d.a(Unknown Source)
	at brut.a.b.a.a.r.d(Unknown Source)
	at brut.a.b.a.a.u.a(Unknown Source)
	at brut.a.b.a.c(Unknown Source)
	at brut.a.a.b(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:31)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:916)

```

**Comment by MohMah** [comment]
Also this when I use enjarify:
```
Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_101

java.io.IOException: Cannot run program "C:\Python37\python.exe" (in directory ""): CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
	at java.lang.ProcessBuilder.start(Unknown Source)
	at the.bytecode.club.bytecodeviewer.Enjarify.apk2Jar(Enjarify.java:62)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:928)
Caused by: java.io.IOException: CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 3 more

```

**Comment by progamerz** [comment]
I get the same first errors

**Comment by FNolte** [comment]
I have the same issue

**Comment by kidandcat** [comment]
same

**Comment by binorelawan** [comment]
no solution yet?
