### ISSUE TITLE
I got the following when uploading the APK which I extracted using APK Extractor tool from Google Play Store.

### ISSUE THREAD

**Issue by strikersps** [Konloch/bytecode-viewer#222]
Errors: 
`Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_192

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:920)
`

`Bytecode Viewer Version: 2.9.11, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 1.8.0_192

java.io.IOException: Unable to delete file: C:\Users\Suraj\.Bytecode-Viewer\bcv_temp\Decoded Resources\res\values-v26\styles.xml
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:30)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$6.run(BytecodeViewer.java:916)
`

**Comment by Konloch** [comment]
Could you try the latest version and let me know if this has solved the issue?
