### ISSUE TITLE
Can't open apk, Error: "java.io.FileNotFoundException system cannot find the file specified"

### ISSUE THREAD

**Issue by nikhilgeo** [Konloch/bytecode-viewer#234]
Can't open an APK, this results in below error !
```
Bytecode Viewer Version: 2.9.18, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 11.0.1
java.io.FileNotFoundException: C:\Users\user1\.Bytecode-Viewer\bcv_temp\aYicoYhnNPLIeqquMHclaxJeQ.jar (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.loadClasses(JarUtils.java:167)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:940)
```

**Comment by Xento** [comment]
When I run it as administrator, it seems to run.

**Comment by Ana06** [comment]
I think this is a duplicated of https://github.com/Konloch/bytecode-viewer/issues/227, but running it as administrator as @Xento proposes solved it for me. 👍
