### ISSUE TITLE
NullPointerException and FileNotFoundException when opening apk

### ISSUE THREAD

**Issue by T3rm1** [Konloch/bytecode-viewer#248]
```
Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 8.1, Java: 1.8.0_131

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:951)


```
```
Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 8.1, Java: 1.8.0_131

brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file:   .xml
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:165)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
	at the.bytecode.club.bytecodeviewer.util.APKTool.decodeResources(APKTool.java:46)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:947)
Caused by: brut.directory.DirectoryException: Error copying file:   .xml
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
	... 5 more
Caused by: java.io.FileNotFoundException: C:\Users\testuser\.Bytecode-Viewer\bcv_temp\ubqBmVKCFHIgQcfikRtYhVTjvzEvjyFf\Decoded Resources\unknown\  .xml (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 7 more
```

APK can be downloaded here: https://apkpure.com/de/jodel-hyperlocal-community/com.tellm.android.app/download/1201201-APK?from=versions%2Fversion

**Comment by steelbytes** [comment]
same.  Any workarounds?
@Konloch

**Comment by hopana** [comment]
I will try to solve the bug

**Comment by hopana** [comment]
This apk file seems to have been encrypted and confused, and some files even have empty names

**Comment by T3rm1** [comment]
> This apk file seems to have been encrypted and confused, and some files even have empty names
Are you saying only "normal" apks are supported?

**Comment by hopana** [comment]
I think so, otherwise even if the apk be decompiled, it's unreadle, just a mess
