### ISSUE TITLE
NullPointerException in BytecodeViewer.resetRecentFilesMenu

### ISSUE THREAD

**Issue by Phoenix616** [Konloch/bytecode-viewer#258]
Just got the following error:

```
Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 7, Java: 1.8.0_221

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.resetRecentFilesMenu(BytecodeViewer.java:1147)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.BOOT(BytecodeViewer.java:580)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:552)
```

Started happening with 2.9.19 and continues to be an issue after updating to 2.9.22.

**Comment by Phoenix616** [comment]
I found out that this bug was introduced somewhere between v2.9.17 (e60ce) and v.2.9.18 (7f227ca).

**Comment by Phoenix616** [comment]
So apparently the reason why it worked in v2.9.17 and not v2.9.19 was because it [was changed](https://github.com/Konloch/bytecode-viewer/commit/7f227ca7e79244db95ca7b8277b6026e549cc58d) from using the recentfiles.bcv file to a json format. And apparently the json file somehow corrupted for me. It contained the list of files twice like:

```json
[
  "path",
  "another/path"
]
[
  "path",
  "another/path"
]
```
Removing the second list of paths stopped the issue from occurring. I guess an invalid files should be caught a little better though
