### ISSUE TITLE
java 14

### ISSUE THREAD

**Issue by javad-salehi** [Konloch/bytecode-viewer#269]
Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 14

java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:260)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:922)

**Comment by pdinklag** [comment]
Let's add Java 15 to this list:
```
java.lang.IllegalArgumentException: Unsupported class file major version 59
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:260)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:922)
```

In the fork that #290 comes from this works just fine.

**Comment by Janmm14** [comment]
and dont forget java 16 is around the corner
