### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by petermill** [Konloch/bytecode-viewer#286]
Stack trace to be send to @konloch _ konloch@gmail.com

Bytecode Viewer Version: 2.9.22, Preview Copy: false, Fat Jar: true, OS: Windows 10, Java: 15.0.1

java.io.FileNotFoundException: C:\Users\peter\.Bytecode-Viewer\bcv_temp\OxwURXLDgjvZXdmFSMUdGqsnD.jar (Le fichier spécifié est introuvable)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.loadClasses(JarUtils.java:168)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:987)

Might be due to java 15, previously i had java 8 and java 13 on my machine

Pierre

**Comment by lukahn** [comment]
I got this working by right clicking on the jar file, going to Properties, and selecting Unblock under Security at the bottom of the General tab.
