### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by guanbo123456** [Konloch/bytecode-viewer#287]
Windows 10

java version "1.8.0_202"

Bytecode-Viewer-2.9.22

C:\Users\admin>java -jar F:\ReverseTools\Bytecode-Viewer-2.9.22.jar
https://the.bytecode.club - Created by @Konloch - Bytecode Viewer 2.9.22, Fat-Jar: true
Start up took 2 seconds
Allowing exec:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\python3.8.exe
java.io.FileNotFoundException: C:\Users\admin\.Bytecode-Viewer\bcv_temp\aoksOUnlKBlEAvTNsJlXnlMNaAHyQfih\cn\jiguang\f\g.j (系统找不到指定的路径。)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:61)
        at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDisassembler.decompileClassNode(KrakatauDisassembler.java:99)
        at the.bytecode.club.bytecodeviewer.gui.ClassViewer$11.doShit(ClassViewer.java:777)
        at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:57)

**Comment by lukahn** [comment]
I got this working by right clicking on the jar file, going to Properties, and selecting Unblock under Security at the bottom of the General tab.

**Comment by ReimarPB** [comment]
For me, it was because I opened it through Windows Search which apparently breaks it. Opening Bytecode Viewer through file explorer works for me.
