### ISSUE TITLE
Unsupported class file major version 60

### ISSUE THREAD

**Issue by Phoenix616** [Konloch/bytecode-viewer#294]
When trying to decompile a jar file that includes classes compiled with Java 16 it will fail to load (and even list) those classes and throw errors like this in the log for each class:

```
Skipping: net/minecraft/world/entity/ai/goal/PathfinderGoalLlamaFollow.class
java.lang.IllegalArgumentException: Unsupported class file major version 60
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
        at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:260)
        at the.bytecode.club.bytecodeviewer.util.JarUtils.put(JarUtils.java:75)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer$8.run(BytecodeViewer.java:904)
```

**Comment by ThexXTURBOXx** [comment]
Works on my machine. Did you try with the newest version `2.10.11`?

![grafik](https://user-images.githubusercontent.com/12763829/123118333-d4ea7f80-d442-11eb-9a12-176add3a4de2.png)

**Comment by Phoenix616** [comment]
Well seeing as 2.10.11 was released after I opened the issue that's pretty much impossible ;)

**Comment by Phoenix616** [comment]
But yes 2.10.11 seems to indeed fix this.
