### ISSUE TITLE
[macOS Big Sur] [2.10.11 ASM 7.1 Fix] Nullpointer Exception when opening .apk file

### ISSUE THREAD

**Issue by snajdovski** [Konloch/bytecode-viewer#296]
Steps to reproduce, open any apk file.

> Bytecode Viewer Version: 2.10.11, Preview Copy: false, Fat Jar: true, OS: Mac OS X, Java: 16.0.1
> 
> java.lang.NullPointerException
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
> 	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:149)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> 

After closing the other window:

> Bytecode Viewer Version: 2.10.11, Preview Copy: false, Fat Jar: true, OS: Mac OS X, Java: 16.0.1
> 
> brut.androlib.AndrolibException: Could not decode XML
> 	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
> 	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
> 	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
> 	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:209)
> 	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137)
> 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:113)
> 	at brut.apktool.Main.cmdDecode(Main.java:160)
> 	at brut.apktool.Main.main(Main.java:72)
> 	at the.bytecode.club.bytecodeviewer.util.APKTool.decodeResources(APKTool.java:39)
> 	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:145)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
> 	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
> 	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
> 	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.<init>(XmlPullWrapperFactory.java:52)
> 	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.newInstance(XmlPullWrapperFactory.java:29)
> 	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:49)
> 	... 10 more

**Comment by snajdovski** [comment]
**Terminal Log:**
```
Start up took 0 seconds
I: Using Apktool 2.3.0 on IXDUFCveFPiUfvtdqNZhVUNMPrSKvUfb.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
brut.androlib.AndrolibException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:209)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:113)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
	at the.bytecode.club.bytecodeviewer.util.APKTool.decodeResources(APKTool.java:39)
	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:145)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.<init>(XmlPullWrapperFactory.java:52)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.newInstance(XmlPullWrapperFactory.java:29)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:49)
	... 10 more
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:149)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
