### ISSUE TITLE
Decompiling Android APK fails in 2.10.11

### ISSUE THREAD

**Issue by JimiSmith** [Konloch/bytecode-viewer#307]
There are two errors that occur

```
Bytecode Viewer Version: 2.10.11, Preview Copy: false, Fat Jar: true, OS: Linux, Java: 11.0.11

brut.androlib.AndrolibException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:209)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:113)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
	at the.bytecode.club.bytecodeviewer.util.APKTool.decodeResources(APKTool.java:39)
	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:145)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.<init>(XmlPullWrapperFactory.java:52)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.newInstance(XmlPullWrapperFactory.java:29)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:49)
	... 10 more

```
and
```
Bytecode Viewer Version: 2.10.11, Preview Copy: false, Fat Jar: true, OS: Linux, Java: 11.0.11

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at the.bytecode.club.bytecodeviewer.util.OpenFile.run(OpenFile.java:149)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

If I unzip the APK, then I can decompile the classes.dex file without any problems
The APK can be decompiled without issue in 2.9.22

**Comment by ThexXTURBOXx** [comment]
Should be fixed in `master`. Could you try with this version please? http://femtopedia.de/bytecodeviewer-2.10.12.jar

**Comment by JimiSmith** [comment]
This issue is resolved now. However there is a  regression in decompilation: #310
