### ISSUE TITLE
Got this while decompiling a valid JVM classfile without obfuscation

### ISSUE THREAD

**Issue by kylestev** [Konloch/bytecode-viewer#31]
```
Bytecode Viewer Version: 2.9.3

java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.TokenMakerBase.addToken(TokenMakerBase.java:134)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.addToken(JavaTokenMaker.java:4747)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.addToken(JavaTokenMaker.java:4729)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.addToken(JavaTokenMaker.java:4717)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.yylex(JavaTokenMaker.java:5164)
	at org.fife.ui.rsyntaxtextarea.modes.JavaTokenMaker.getTokenList(JavaTokenMaker.java:4797)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.getTokenListForLine(RSyntaxDocument.java:416)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.getLineWidth(SyntaxView.java:301)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.calculateLongestLine(SyntaxView.java:110)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.refreshFontMetrics(RSyntaxTextArea.java:1993)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.addNotify(RSyntaxTextArea.java:453)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at javax.swing.JViewport.addNotify(JViewport.java:368)
	at java.awt.Container.addNotify(Container.java:2773)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1119)
	at java.awt.Container.add(Container.java:415)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$14.doShit(ClassViewer.java:859)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)

```

**Comment by Konloch** [comment]
Could you provide the classfile you used and the decompiler you selected?

**Comment by TheBiblMan** [comment]
needs to be threaded

**Comment by TheBiblMan** [comment]
properly

**Comment by Konloch** [comment]
Suppressed all syntax-highlighting related exceptions caused via RSyntaxTextArea.
