### ISSUE TITLE
Java 16: Crash with custom theme 

### ISSUE THREAD

**Issue by Janmm14** [Konloch/bytecode-viewer#312]
```
https://the.bytecode.club - Created by @Konloch - Bytecode Viewer 2.10.12, Fat-Jar: true
Exception in thread "main" java.lang.IllegalAccessError: class com.github.weisj.darklaf.ui.internalframe.DarkInternalFrameTitlePane$DarkTitlePaneLayout (in unnamed module @0x5403f35f) cannot access class sun.swing.SwingUtilities2 (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x5403f35f
        at com.github.weisj.darklaf.ui.internalframe.DarkInternalFrameTitlePane$DarkTitlePaneLayout.minimumLayoutSize(DarkInternalFrameTitlePane.java:341)
        at java.desktop/java.awt.Container.minimumSize(Container.java:1876)
        at java.desktop/java.awt.Container.getMinimumSize(Container.java:1860)
        at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1762)
        at java.desktop/javax.swing.plaf.basic.BasicInternalFrameUI$Handler.minimumLayoutSize(BasicInternalFrameUI.java:1619)
        at java.desktop/javax.swing.plaf.basic.BasicInternalFrameUI.getMinimumSize(BasicInternalFrameUI.java:405)
        at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1760)
        at java.desktop/javax.swing.plaf.basic.BasicInternalFrameUI$Handler.propertyChange(BasicInternalFrameUI.java:1758)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:342)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:334)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:267)
        at java.desktop/java.awt.Component.firePropertyChange(Component.java:8713)
        at java.desktop/javax.swing.JInternalFrame.setTitle(JInternalFrame.java:1013)
        at the.bytecode.club.bytecodeviewer.gui.resourceviewer.WorkPaneMainComponent.<init>(WorkPaneMainComponent.java:59)
        at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI.<init>(MainViewerGUI.java:70)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:183)
```

**Comment by ThexXTURBOXx** [comment]
Known issue with DarkLaf: https://github.com/weisJ/darklaf/issues/234

For now, see [this comment](https://github.com/weisJ/darklaf/issues/234#issuecomment-816953525) for a workaround. Please note that it is recommended to run BCV with Java 8 for now (we may not know about many issues that still may arise).

**Comment by Janmm14** [comment]
yeah ik about that cli flag
