### ISSUE TITLE
Unable to start when switching to dark theme

### ISSUE THREAD

**Issue by MrIkso** [Konloch/bytecode-viewer#322]
**OS**: Windows 10 x64 21H1
Java 

> java 16.0.1 2021-04-20
> Java(TM) SE Runtime Environment (build 16.0.1+9-24)
> Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**Log**
``` java -jar Bytecode-Viewer-2.10.13.jar
Bytecode Viewer 2.10.13 [FatJar] - Created by @Konloch
https://bytecodeviewer.com - https://the.bytecode.club
Exception in thread "main" java.lang.IllegalAccessError: class com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge (in unnamed module @0x2a54a73f) cannot access class sun.swing.DefaultLookup (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x2a54a73f
        at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge.getInputMap(DarkTabbedPaneUIBridge.java:860)
        at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge.installKeyboardActions(DarkTabbedPaneUIBridge.java:782)
        at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUIBridge.installUI(DarkTabbedPaneUIBridge.java:228)
        at com.github.weisj.darklaf.ui.tabbedpane.DarkTabbedPaneUI.installUI(DarkTabbedPaneUI.java:129)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
        at java.desktop/javax.swing.JTabbedPane.setUI(JTabbedPane.java:253)
        at java.desktop/javax.swing.JTabbedPane.updateUI(JTabbedPane.java:269)
        at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:231)
        at java.desktop/javax.swing.JTabbedPane.<init>(JTabbedPane.java:196)
        at the.bytecode.club.bytecodeviewer.gui.resourceviewer.WorkPaneMainComponent.<init>(WorkPaneMainComponent.java:64)
        at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI.<init>(MainViewerGUI.java:70)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:180)
``

**Comment by Janmm14** [comment]
Duplicate of #312

**Comment by MrIkso** [comment]
Oh, yes, sorry. Issue closed. Why? Maybe use another library to switch themes? Im using [FlatLaf](https://github.com/JFormDesigner/FlatLaf). Working perfect on java 16)

**Comment by Janmm14** [comment]
Its closed because next release of bytecode-viewer will have the issue fixed by using a snapshot of darklaf.

**Comment by Janmm14** [comment]
You can download inofficial dev builds here: https://ci.janmm14.de/job/public%7Eother%7EBytecodeViewerMaven/

**Comment by MrIkso** [comment]
> Its closed because next release of bytecode-viewer will have the issue fixed by using a snapshot of darklaf.

Okay, I close the issue.
