### ISSUE TITLE
2.10.13 unable to view or decompile

### ISSUE THREAD

**Issue by jredfox** [Konloch/bytecode-viewer#324]
Test Jar: [TestApp.jar.zip](https://github.com/Konloch/bytecode-viewer/files/6835813/TestApp.jar.zip)

I open it up look at a class nothing happens. I try decompile and save all classes also nothing happnes

**Comment by ThexXTURBOXx** [comment]
Not reproducible on my machine.
Which operating system do you use? If it's MacOS, there are quite some reports that under certain conditions, it doesn't work correctly
![grafik](https://user-images.githubusercontent.com/12763829/126062608-d9936348-b0ac-4310-ad1b-01afab14d527.png)

**Comment by jredfox** [comment]
@ThexXTURBOXx 
```java
C:\Users\jredfox>java -jar C:\Users\jredfox\Desktop\Bytecode-Viewer-2.9.11.jar
https://the.bytecode.club - Created by @Konloch - Bytecode Viewer 2.9.11, FatJar: true
Start up took 0 seconds
java.lang.NullPointerException
        at the.bytecode.club.bootloader.Boot.populateLibsDirectory(Boot.java:327)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:408)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.plaf.basic.BasicTreeUI.getPreferredSize(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI.getPreferredSize(Unknown Source)
        at javax.swing.JComponent.getPreferredSize(Unknown Source)
        at javax.swing.JTree.getScrollableTracksViewportWidth(Unknown Source)
        at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
        at java.awt.Container.layout(Unknown Source)
        at java.awt.Container.doLayout(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validate(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
        ```
