### ISSUE TITLE
You need to set you Python 2.7 executable path

### ISSUE THREAD

**Issue by XNepster** [Konloch/bytecode-viewer#33]
When i drop classes_dex2jar.jar into it. It give two types of error.

1. You need to set your Python 2.7 executable path

2.  I downloaded the python-2.7.msi but it give me this error Message. 

java.io.IOException: Cannot run program "E:\Aamir Projects\python-2.7.msi": CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(Unknown Source)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDisassembler.decompileClassNode(KrakatauDisassembler.java:51)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$13.doShit(ClassViewer.java:731)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 4 more

**Comment by Konloch** [comment]
You need to install Python with the MSI, then navigate to the Python.exe, I (now thanks to storyyeller) recommend you try out PyPy for speed as an alternative to Python.
