### ISSUE TITLE
Unable to open large jar file

### ISSUE THREAD

**Issue by fbibad** [Konloch/bytecode-viewer#330]
I have a large jar file (30 MB) that I drag in, the Files field light up as well the workspace, but nothing is there, I can try to search for strings but nothing happens, and if i try to clikc "+" or "-" button next to "Extract" checkbox it crashes

**Comment by Janmm14** [comment]
please try to open BCV via console `java -jar Bytecode-Viewer-2.10.14.jar` to see the error

**Comment by fbibad** [comment]
i got `java.util.zip.ZipException: invalid entry CRC (expected 0x0 but got 0xa10e2b06)`, then spams bunch of stuff:
`     at java.util.zip.ZipInputStream.readEnd(Unknown Source)
      at java.util.zip.ZipInputStream.read(Unknown Source)
      at java.io.FilterInputStream.read(Unknown Source)
      at the.bytecode.club.bytecodeviewer.util.MiscUtils.getBytes(MiscUtils.java:292)
      at the.bytecode.club.bytecodeviewer.resources.ResourceContainerImporter.addResource(ResourceContainerImporter.jav`
  ...

**Comment by ThexXTURBOXx** [comment]
Is the jar file you are trying to import copyrighted or can you share the file with us to investigate the problem? On first glance, I would guess that the jar file is corrupt, but I just want to make sure

**Comment by Janmm14** [comment]
> Is the jar file you are trying to import copyrighted or can you share the file with us to investigate the problem? On first glance, I would guess that the jar file is corrupt, but I just want to make sure

The JVM can load jars with invalid CRC afaik.


I suggest that you try to use recaf by col-e to open the jar file. If you don't like its gui, you can use export in the top menu directly after loading to save it as new, valid jar file.

**Comment by ThexXTURBOXx** [comment]
> The JVM can load jars with invalid CRC afaik.
The JVM can, but the `ZipInputStream` throws an Exception if the CRC check fails

**Comment by Konloch** [comment]
Could you provide the full stack trace?
