### ISSUE TITLE
java.lang.NullPointerException SettingsDialogue.java:93

### ISSUE THREAD

**Issue by selankon** [Konloch/bytecode-viewer#333]
Hi, I get this error:

```
Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytcode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.10.14 [FatJar], OS: Linux, Java: 11.0.10

	
	at the.bytecode.club.bytecodeviewer.gui.components.SettingsDialogue.getName(SettingsDialogue.java:93)
	at java.desktop/com.sun.java.swing.plaf.gtk.GTKStyle.getInsets(GTKStyle.java:338)
	at java.desktop/javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:915)
	at java.desktop/javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:270)
	at java.desktop/javax.swing.plaf.synth.SynthScrollPaneUI.updateStyle(SynthScrollPaneUI.java:140)
	at java.desktop/javax.swing.plaf.synth.SynthScrollPaneUI.installDefaults(SynthScrollPaneUI.java:133)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI.installUI(BasicScrollPaneUI.java:236)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JScrollPane.setUI(JScrollPane.java:378)
	at java.desktop/javax.swing.JScrollPane.updateUI(JScrollPane.java:391)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:306)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:324)
	at the.bytecode.club.bytecodeviewer.gui.components.SettingsDialogue.<init>(SettingsDialogue.java:43)
	at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI.buildSettingsMenu(MainViewerGUI.java:447)
	at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI.<init>(MainViewerGUI.java:295)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:183)
```

**Comment by Konloch** [comment]
The latest version v2.10.15 should fix this issue, if it doesn't please let me know and I will resolve it
