### ISSUE TITLE
com.googlecode.d2j.DexException: fail convert code for

### ISSUE THREAD

**Issue by TechComet** [Konloch/bytecode-viewer#334]
Hi,

this problem on v2.10.14
its work without problems on bytecode-viewer v2.9.20

```
com.googlecode.d2j.DexException: fail convert code for Landroidx/constraintlayout/solver/widgets/ConstraintWidget;.applyConstraints(Landroidx/constraintlayout/solver/LinearSystem;ZLandroidx/constraintlayout/solver/SolverVariable;Landroidx/constraintlayout/solver/SolverVariable;Landroidx/constraintlayout/solver/widgets/ConstraintWidget$DimensionBehaviour;ZLandroidx/constraintlayout/solver/widgets/ConstraintAnchor;Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;IIIIFZZIIIFZ)V
        at com.googlecode.d2j.dex.ExDex2Asm.convertCode(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar.to(Unknown Source)
        at the.bytecode.club.bytecodeviewer.util.Dex2Jar.dex2Jar(Dex2Jar.java:45)
        at the.bytecode.club.bytecodeviewer.resources.importing.impl.APKResourceImporter.open(APKResourceImporter.java:45)
        at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:90)
        at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:62)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.mergeProviderType(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.mergeTypeToSubRef(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.copyTypes(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.fixTypes(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.analyze(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer.transform(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar$2.optimize(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertCode(Unknown Source)
        ... 12 more

```

I have other problem
v2.9.20 and v2.10.14 not decompile complete some files to end

**Comment by TechComet** [comment]
v2.10.15 now work and decompile apk file and show this problem

```
com.googlecode.d2j.DexException: fail convert code for Landroidx/constraintlayout/solver/widgets/ConstraintWidget;.applyConstraints(Landroidx/constraintlayout/solver/LinearSystem;ZLandroidx/constraintlayout/solver/SolverVariable;Landroidx/constraintlayout/solver/SolverVariable;Landroidx/constraintlayout/solver/widgets/ConstraintWidget$DimensionBehaviour;ZLandroidx/constraintlayout/solver/widgets/ConstraintAnchor;Landroidx/constraintlayout/solver/widgets/ConstraintAnchor;IIIIFZZIIIFZ)V
        at com.googlecode.d2j.dex.ExDex2Asm.convertCode(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar.to(Unknown Source)
        at the.bytecode.club.bytecodeviewer.util.Dex2Jar.dex2Jar(Dex2Jar.java:45)
        at the.bytecode.club.bytecodeviewer.resources.importing.impl.APKResourceImporter.open(APKResourceImporter.java:45)
        at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:90)
        at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:62)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.mergeProviderType(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.mergeTypeToSubRef(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.copyTypes(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.fixTypes(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.analyze(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.TypeTransformer.transform(Unknown Source)
        at com.googlecode.d2j.dex.Dex2jar$2.optimize(Unknown Source)
        at com.googlecode.d2j.dex.Dex2Asm.convertCode(Unknown Source)
```

**Comment by ThexXTURBOXx** [comment]
Could you please try if this snapshot fixes your issue? https://github.com/Konloch/bytecode-viewer/suites/3452234946/artifacts/81956386

**Comment by TechComet** [comment]
Yes .. Decompile success


but show this error
```
Detail Error Information in File ./ihWbphYfxAFwYIAKfColdHnxorOMxnuh-error.zip
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues [no attachment support, not preferred]
    dex2jar@googlegroups.com
```

[ihWbphYfxAFwYIAKfColdHnxorOMxnuh-error.zip](https://github.com/Konloch/bytecode-viewer/files/6982107/ihWbphYfxAFwYIAKfColdHnxorOMxnuh-error.zip)

**Comment by ThexXTURBOXx** [comment]
Could you maybe try again with this build: https://github.com/Konloch/bytecode-viewer/suites/3480941031/artifacts/82803826

It is very strange that the error does not contain the lines in the code where the errors occurr 🤔 
Also, I believe that this is a pretty hard exception to fix, but I will try my best.

**Comment by ThexXTURBOXx** [comment]
Oh, and also: If you are able to share the APK (i.e. you have the license to do so), could you maybe share it with me such that i can further look into that issue? :)

**Comment by TechComet** [comment]
this app I'm have the license and have source code if you needed

this like that app and have self problem
[Info Car.zip](https://github.com/Konloch/bytecode-viewer/files/6982382/Info.Car.zip)


[IbmYiXBPkjBfoeUsAgmMPwBkQNXguXfg-error.zip](https://github.com/Konloch/bytecode-viewer/files/6982358/IbmYiXBPkjBfoeUsAgmMPwBkQNXguXfg-error.zip)

-----------------Edit----------------
 Bytecode-Viewer-2.10.16-SNAPSHOT it's work and not found any problem

but found problem with Fernflower
create new issus here -- or this not bytecode-viewer problem?

**Comment by ThexXTURBOXx** [comment]
Oh, that's very good that it is working now in 2.10.16-SNAPSHOT. Then, this issue can most likely be closed @Konloch

For the issue regarding Fernflower: Yes, a new issue might be best here. We will investigate the issue then and see if it is related to BCV or FernFlower itself :)

Thank you for reporting back!
