### ISSUE TITLE
Invalid Constant Pool

### ISSUE THREAD

**Issue by sebint** [Konloch/bytecode-viewer#337]
JD-GUI Error! Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytecode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.10.15 [Fat Jar], OS: Windows 10, Java: 11.0.10

Suggested Fix: Click refresh class, if it fails again try another decompiler.

Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytecode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.10.15 [Fat Jar], OS: Windows 10, Java: 11.0.10

org.jd.core.v1.service.deserializer.classfile.ClassFileFormatException: Invalid constant pool
	at the.bytecode.club.bytecodeviewer.decompilers.jdgui.JDGUIClassFileUtil.ExtractDirectoryPath(JDGUIClassFileUtil.java:54)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.JDGUIDecompiler.decompileClassNode(JDGUIDecompiler.java:85)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:107)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:158)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Janmm14** [comment]
I suggest trying another decompiler

**Comment by Konloch** [comment]
Krakatau, FernFlower, Procyon or CFR should handle that classfile, JDGUI is designed for quick decompilcation so it is very fast compared to the others.
