### ISSUE TITLE
Smali Disassembler - Critical BCV Error

### ISSUE THREAD

**Issue by wwwghubwoo** [Konloch/bytecode-viewer#339]
Hi, I can't get the Smali Disassembler working on 2.10.15.  It seems to be working fine on 2.9.22.  I've tried newer versions of Java but that didn't seem to help.

Bytecode Viewer Version: 2.10.15 [Fat Jar], OS: Mac OS X, Java: 1.8.0_202-ea

![image](https://user-images.githubusercontent.com/43049032/127697163-b4d136f6-6ff4-418c-95af-29063f1f8c7a.png)

```
Error log in console:
jar2dex /Users/mandible/.Bytecode-Viewer/bcv_temp/tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq.class -> tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq-jar2dex.dex
call com.android.dx.command.Main.main[--dex, --no-strict, --output=/Users/mandible/Desktop/Save1/assessments/2021_07_FNB/tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq-jar2dex.dex, /Users/mandible/.Bytecode-Viewer/bcv_temp/tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq.class]
baksmali /Users/mandible/.Bytecode-Viewer/bcv_temp/tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq.dex -> tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq-out
com.googlecode.d2j.DexException: Error process class: [72]Lnz/co/mcom/phone/activities/MobilitiActivity;
	at com.googlecode.d2j.reader.DexFileReader.accept(Unknown Source)
	at com.googlecode.d2j.reader.DexFileReader.accept(Unknown Source)
	at com.googlecode.d2j.smali.Baksmali.to(Unknown Source)
	at com.googlecode.d2j.smali.BaksmaliCmd.doCommandLine(Unknown Source)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(Unknown Source)
	at com.googlecode.d2j.smali.BaksmaliCmd.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.SmaliDisassembler.decompileClassNode(SmaliDisassembler.java:75)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:107)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:158)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.SecurityException: BCV is awesome, blocking write(tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq-out/nz/co/mcom/phone/activities);
	at the.bytecode.club.bytecodeviewer.util.SecurityMan.checkWrite(SecurityMan.java:339)
	at sun.nio.fs.UnixPath.checkWrite(UnixPath.java:801)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:376)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at com.googlecode.d2j.smali.BaksmaliDexFileVisitor$1.visitEnd(Unknown Source)
	... 10 more
java.io.FileNotFoundException: Source 'tempxqeZiIKbCXwIDZdrtZTdkAFureTCimWq-out' does not exist
	at org.apache.commons.io.FileUtils.validateMoveParameters(FileUtils.java:3124)
	at org.apache.commons.io.FileUtils.moveDirectory(FileUtils.java:2220)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.SmaliDisassembler.decompileClassNode(SmaliDisassembler.java:87)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:107)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:158)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Konloch** [comment]
Would you be able to provide the class file/APK? (Only if you own the rights to it)

**Comment by wwwghubwoo** [comment]
I don't have the rights sadly

**Comment by wwwghubwoo** [comment]
I did some testing, it seems that this happens for several apks and on Windows and Mac
