### ISSUE TITLE
Add option to add additional jar(s)/path(s) to Krakatau when decompiling apk files

### ISSUE THREAD

**Issue by FourPee** [Konloch/bytecode-viewer#34]
Found an issue when decompiling sources from apk requires android.app.Activity class sources to continue work of decompilation files.
Solved by calling externally krakatau  with '-path' option set out of box bytecode-viewer.

stacktrace:

<code>
Process:

Krakatau  Copyright (C) 2012-14  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

processing target XXX 1 remaining
Loading XXX
Loading android/app/Activity

Error:

Traceback (most recent call last):
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\decompile.py", line 139, in <module>
    decompileClass(path, targets, args.out, args.skip)
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\decompile.py", line 85, in decompileClass
    c = e.getClass(target)
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\Krakatau\environment.py", line 23, in getClass
    result = self._loadClass(name, subclasses)
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\Krakatau\environment.py", line 71, in _loadClass
    new.loadSupers(self, name, subclasses)
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\Krakatau\classfile.py", line 102, in loadSupers
    superclass = self.env.getClass(self.supername, subclasses + (name,), partial=True)
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\Krakatau\environment.py", line 23, in getClass
    result = self._loadClass(name, subclasses)
  File "C:\Users\XXX\.Bytecode-Viewer\krakatau_2\Krakatau-master\Krakatau\environment.py", line 67, in _loadClass
    raise ClassLoaderError('ClassNotFoundException', name)
Krakatau.error.ClassLoaderError: 
ClassNotFoundException: android/app/Activity

Exit Value is 1
Bytecode Viewer Version: 2.9.3

java.io.FileNotFoundException: C:\Users\XXX\.Bytecode-Viewer\bcv_temp\CCysZBjkqwIytZrMxGvcBfVrTeCmzNNj\com\cizek\wifileaks\Crossway.java (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at me.konloch.kontainer.io.DiskReader.loadAsString(DiskReader.java:63)
	at the.bytecode.club.bytecodeviewer.decompilers.KrakatauDecompiler.decompileClassNode(KrakatauDecompiler.java:86)
	at the.bytecode.club.bytecodeviewer.gui.ClassViewer$13.doShit(ClassViewer.java:703)
	at the.bytecode.club.bytecodeviewer.gui.PaneUpdaterThread.run(PaneUpdaterThread.java:16)
</code>

**Comment by Konloch** [comment]
Krakatau -path support is finished in 2.9.4, I'm just working on DJ-Core integration then it'll be ready for release.

Thanks for the in-depth report however! If you run into any more bugs don't hesitate to report them!
