### ISSUE TITLE
Malformed input exception

### ISSUE THREAD

**Issue by KovacsGG** [Konloch/bytecode-viewer#341]
Hi! I encounter the following error when I try to view seemingly any .jar by drag'n'dropping it.

```
Bytecode Viewer Version: 2.10.15 [Fat Jar], OS: Windows 10, Java: 16.0.2

java.lang.IllegalArgumentException: malformed input off : 1, length : 1
	at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
	at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
	at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:978)
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2273)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:208)
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66)
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
	at the.bytecode.club.bytecodeviewer.resources.ResourceContainerImporter.importZipInputStream(ResourceContainerImporter.java:153)
	at the.bytecode.club.bytecodeviewer.resources.ResourceContainerImporter.importAsZip(ResourceContainerImporter.java:74)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.ZipResourceImporter.open(ZipResourceImporter.java:24)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:90)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:62)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	... 14 more
```

My uneducated guess is that the issue might have to do something with the encoding of the file names, since I'm using a non-english system.

[Example file](https://drive.google.com/file/d/15wQWO-rKTT6aChhLEl2zP_RYxRR1Z2sX/view?usp=sharing)

**Comment by Konloch** [comment]
Hi, I've tried opening the file with BCV and I also encounter a similar issue. However I also cannot open the jar with 7Zip so maybe I was unable to download it correctly, can you verify the same file can be opened with 7Zip or another archive viewer? it's possible the zip file is corrupt. I will look into this more though, thank you for the report!

**Comment by ThexXTURBOXx** [comment]
I am able to view the contents with `WinRAR`. After insepcting the `jar` file with Notepad++, I noticed that the contents are not actually compressed, which is very weird.
Thus, I re-packaged the contents of the jar file into a normal `zip` container. Then, BCV had no problems reading the file.
This means that the file names are not the problem, but rather the weird packaging of the `jar`. Where or how did you get this particular `jar` file?

**Comment by ThexXTURBOXx** [comment]
I now tried inspecting the file with `zipinfo` and it actually shows a warning: `260 extra bytes at beginning or within zipfile`.
Thus, the problem doesn't seem to be related to BCV

```
$> zipinfo -v jsoup.jar
Archive:  jsoup.jar
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                    798672 (00000000000C2FD0h)
  Actual end-cent-dir record offset:        798650 (00000000000C2FBAh)
  Expected end-cent-dir record offset:      798390 (00000000000C2EB6h)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 257 entries.
  The central directory is 21875 (0000000000005573h) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 776515 (00000000000BD943h).

warning [jsoup.jar]:  260 extra bytes at beginning or within zipfile
  (attempting to process anyway)
```

**Comment by KovacsGG** [comment]
Thank you, your insight was very helpful!

The jar was part of a deb package. Extracting that with 7zip at some point seems to have also inflated the jars.

Extracting it with winRAR on the other hand left the jars compressed, valid for 7zip and BCV.

Clearly I don't know how my tools work, but you are right, they do work, including BCV. This is not an issue.

**Comment by ThexXTURBOXx** [comment]
No problem! Thanks for reporting anyways! :)
