### ISSUE TITLE
Cannot preview dex file at version 2.10.16

### ISSUE THREAD

**Issue by PrimarchDatNT** [Konloch/bytecode-viewer#346]
C:\Users\DatNT\Desktop\classes.dex
java.lang.IllegalArgumentException
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:249)
        at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:124)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:209)
        at org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:108)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:476)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:425)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:533)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:134)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:234)
        at the.bytecode.club.bytecodeviewer.util.Dex2Jar.dex2Jar(Dex2Jar.java:42)
        at the.bytecode.club.bytecodeviewer.resources.importing.impl.DEXResourceImporter.open(DEXResourceImporter.java:52)
        at the.bytecode.club.bytecodeviewer.CommandLineInput.executeCommandLine(CommandLineInput.java:203)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:223)
C:\Users\DatNT\Desktop\classes2.dex
java.io.FileNotFoundException: File system element for parameter 'source' does not exist: 'C:\Users\DatNT\classes2.dex'
        at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2719)
        at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2751)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:840)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
        at the.bytecode.club.bytecodeviewer.resources.importing.impl.DEXResourceImporter.open(DEXResourceImporter.java:44)
        at the.bytecode.club.bytecodeviewer.CommandLineInput.executeCommandLine(CommandLineInput.java:203)
        at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:223

**Comment by ThexXTURBOXx** [comment]
Are you able to share the DEX file, so I can debug the problem?

**Please only share the DEX file if you have the appropriate legal rights to do so. If not, please share the link to the Google Play Entry or some other uploader.**

**Comment by ThexXTURBOXx** [comment]
This error could be fixed in [this release](https://github.com/Konloch/bytecode-viewer/suites/3683946849/artifacts/89746958).
Can you confirm that this is the case? :)

**Comment by Konloch** [comment]
Hi, this issue we believe is fixed. If you experience this issue in the future on the latest version, please open a new issue and let us know.
