### ISSUE TITLE
in-pane search breaks

### ISSUE THREAD

**Issue by TobTobXX** [Konloch/bytecode-viewer#355]
When I try to use the file-specific search (Ctrl-F), BCV breaks:

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 3
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at the.bytecode.club.bytecodeviewer.gui.components.MethodsRenderer.getListCellRendererComponent(MethodsRenderer.java:46)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getDisplaySize(BasicComboBoxUI.java:1446)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getMinimumSize(BasicComboBoxUI.java:999)
	at com.github.weisj.darklaf.ui.combobox.DarkComboBoxUI.getMinimumSize(DarkComboBoxUI.java:288)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getPreferredSize(BasicComboBoxUI.java:988)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:733)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1808)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at java.desktop/javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:103)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1808)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:732)
	at com.github.weisj.darklaf.delegate.ScrollLayoutManagerDelegate.layoutContainer(ScrollLayoutManagerDelegate.java:120)
	at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI$1.layoutContainer(DarkScrollPaneUI.java:179)
	at java.desktop/java.awt.Container.layout(Container.java:1538)
	at java.desktop/java.awt.Container.doLayout(Container.java:1527)
	at java.desktop/java.awt.Container.validateTree(Container.java:1723)
	at java.desktop/java.awt.Container.validate(Container.java:1658)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:742)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1883)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The search bar disappears (!) and the workspace tab breaks (can't close it anymore). Happens with any decompiler. Ask me about any more necessary informations.

Thank you for your work!!! :hugs:

**Comment by TobTobXX** [comment]
hmm... weird, I deleted the ~/.Bytecode-Viewer directory and set it up again and the bug went away.
