### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dzh1gurd4** [Konloch/bytecode-viewer#380]
Bytecode Viewer Version: 2.11.0 [Fat Jar], OS: Windows 10, Java: 1.8.0_281

java.lang.ArrayIndexOutOfBoundsException: 15873
	at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:3726)
	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:3741)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:454)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at the.bytecode.club.bytecodeviewer.api.ASMUtil.bytesToNode(ASMUtil.java:42)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:242)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.ClassResourceImporter.open(ClassResourceImporter.java:47)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:87)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:59)
	at java.lang.Thread.run(Unknown Source)

.class file: https://drive.google.com/file/d/1K0qxedgfHW-x5fwy-WuflXERInJaBQKn/view

**Comment by ThexXTURBOXx** [comment]
Seems reproducable, but are you sure that the class file you attached is indeed valid?
None of my tools seems to be able to parse it properly.
In fact, even `javap` has problems reading it:
![grafik](https://user-images.githubusercontent.com/12763829/151404884-6bb75e49-2706-40ea-8f74-9deb059412e5.png)
