### ISSUE TITLE
error

### ISSUE THREAD

**Issue by UltimateBoi** [Konloch/bytecode-viewer#382]
```
Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytecode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.11.0 [Fat Jar], OS: Windows 10, Java: 16.0.1

java.io.FileNotFoundException: C:\Users\Ultimate\Documents\cheeto lmfao.zip (Access is denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.CFRDecompiler.zip(CFRDecompiler.java:323)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.CFRDecompiler.decompileToZip(CFRDecompiler.java:311)
	at the.bytecode.club.bytecodeviewer.resources.ResourceDecompiling.lambda$null$5(ResourceDecompiling.java:159)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by ThexXTURBOXx** [comment]
`Access is denied`: Could you make sure that bytecode-viewer has the appropriate rights to read the file?

**Comment by Konloch** [comment]
This should be fixed with https://github.com/Konloch/bytecode-viewer/commit/ab169afa370680deab76bafe52c6097ccf8e7ee6 thank you for the report
