### ISSUE TITLE
java.lang.SecurityException: BCV is awesome! Blocking exec: C:\Windows\System32\bg-BG\windows.ui.xaml.dll.mui

### ISSUE THREAD

**Issue by disagreeing** [Konloch/bytecode-viewer#386]
```
java.lang.SecurityException: BCV is awesome! Blocking exec: C:\Windows\System32\bg-BG\windows.ui.xaml.dll.mui`
	at the.bytecode.club.bytecodeviewer.util.SecurityMan.checkExec(SecurityMan.java:163)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1096)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.KrakatauDisassembler.decompileClassNode(KrakatauDisassembler.java:79)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:107)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:158)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Janmm14** [comment]
Well - it does not look like that file should get executed by BCV when it wants to start python/pypy with krakatau
