### ISSUE TITLE
BCV is awesome, blocking write

### ISSUE THREAD

**Issue by Whalte** [Konloch/bytecode-viewer#389]
Bytecode Viewer Version: 2.11.0

Please send this to [konloch@gmail.com](mailto:konloch@gmail.com).

Bytecode Viewer Version: 2.11.0

java.lang.SecurityException: BCV is awesome, blocking write(/Users/hekangbin);
	at the.bytecode.club.bytecodeviewer.util.SecurityMan.checkWrite(SecurityMan.java:342)
	at java.io.File.canWrite(File.java:791)
	at sun.awt.shell.ShellFolder.canWrite(ShellFolder.java:368)
	at com.apple.laf.AquaFileChooserUI$2.propertyChange(AquaFileChooserUI.java:403)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8434)
	at javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:598)
	at javax.swing.JFileChooser.<init>(JFileChooser.java:344)
	at javax.swing.JFileChooser.<init>(JFileChooser.java:296)
	at the.bytecode.club.bytecodeviewer.gui.components.FileChooser.<init>(FileChooser.java:43)
	at the.bytecode.club.bytecodeviewer.util.DialogUtils.fileChooser(DialogUtils.java:95)
	at the.bytecode.club.bytecodeviewer.util.DialogUtils.fileChooser(DialogUtils.java:84)
	at the.bytecode.club.bytecodeviewer.util.DialogUtils.fileChooser(DialogUtils.java:76)
	at the.bytecode.club.bytecodeviewer.resources.ExternalResources.selectJavac(ExternalResources.java:261)
	at the.bytecode.club.bytecodeviewer.compilers.impl.JavaCompiler.compile(JavaCompiler.java:62)
	at the.bytecode.club.bytecodeviewer.gui.resourceviewer.BytecodeViewPanel.compile(BytecodeViewPanel.java:91)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.compile(BytecodeViewer.java:483)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.autoCompileSuccessful(BytecodeViewer.java:457)
	at the.bytecode.club.bytecodeviewer.resources.ResourceDecompiling.lambda$decompileSaveAll$8(ResourceDecompiling.java:54)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Decompile Thread" java.lang.SecurityException: BCV is awesome, blocking write(/Users/hekangbin);
	at the.bytecode.club.bytecodeviewer.util.SecurityMan.checkWrite(SecurityMan.java:342)
	at java.io.File.canWrite(File.java:791)
	at sun.awt.shell.ShellFolder.canWrite(ShellFolder.java:368)
	at com.apple.laf.AquaFileChooserUI$2.propertyChange(AquaFileChooserUI.java:403)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8434)
	at javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:598)
	at javax.swing.JFileChooser.<init>(JFileChooser.java:344)
	at javax.swing.JFileChooser.<init>(JFileChooser.java:296)
	at the.bytecode.club.bytecodeviewer.gui.components.FileChooser.<init>(FileChooser.java:43)
	at the.bytecode.club.bytecodeviewer.gui.components.FileChooser.<init>(FileChooser.java:39)
	at the.bytecode.club.bytecodeviewer.resources.ResourceDecompiling.lambda$decompileSaveAll$8(ResourceDecompiling.java:57)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Whalte** [comment]
Temporarily resolved by setting '-Djava.io.tmpdir=/Users/hekangbin' in java -jar command line.
