### ISSUE TITLE
Error while opening the apk file

### ISSUE THREAD

**Issue by kirantpatil** [Konloch/bytecode-viewer#39]
I am getting below error while trying to open apk file.

--------------

Bytecode Viewer Version: 2.9.5

java.io.FileNotFoundException: /home/kpatil/.Bytecode-Viewer/bcv_temp/joOUFcfnpWvvKnAxXdpRHrFWfPzTZQGo.apk (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at the.bytecode.club.bytecodeviewer.JarUtils.loadResources(JarUtils.java:80)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:615)

--------------
Bytecode Viewer Version: 2.9.5

java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at brut.a.d.c.b.a(Unknown Source)
	at c.d.a.a.a(Unknown Source)
	at c.d.b.a.a.d.a(Unknown Source)
	at c.d.b.a.a.b.b(Unknown Source)
	at c.d.b.a.a.b.a(Unknown Source)
	at brut.a.d.b.p.a(Unknown Source)
	at brut.a.d.b.o.a(Unknown Source)
	at brut.a.d.b.o.b(Unknown Source)
	at brut.a.d.b.j.a(Unknown Source)
	at brut.a.d.a.b(Unknown Source)
	at brut.a.a.c(Unknown Source)
	at brut.a.c.a(Unknown Source)
	at brut.apktool.Main.a(Unknown Source)
	at brut.apktool.Main.main(Unknown Source)
	at the.bytecode.club.bytecodeviewer.APKTool.decodeResources(APKTool.java:13)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer$3.run(BytecodeViewer.java:614)

**Comment by Konloch** [comment]
Could you please provide the APK?

**Comment by kirantpatil** [comment]
The APK can be downloaded from this link,
https://www.nordicsemi.com/eng/nordic/Products/nRF-Master-Control-Panel-application/nRF-Master-Control-Panel-APK-for-Android-4.3/36818

**Comment by Konloch** [comment]
Confirmed fixed for 2.9.7 preview 2.
