### ISSUE TITLE
Out of Memory Everytime i run it (worked fine earlier)

### ISSUE THREAD

**Issue by tarun0** [Konloch/bytecode-viewer#451]
It worked fine initially for like 2-3 times but after that it always hangs on the step and while i waited for some time today, it threw Out of Memory exception. 

Happened while using command line as well as on dragging the apk on UI.

System: MacOS Monterey 12.4; 8GB RAM

Bytecode Viewer 2.11.2 [Fat Jar] - Created by @Konloch
https://bytecodeviewer.com - https://the.bytecode.club
Warning: the fonts "Times" and "Lucida Bright" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Extracting Krakatau
Start up took 4 seconds
Opening...myapk_apkcombo.com.apk

I: Using Apktool 2.6.1 on AqIMUKmjlbgmPUEySdIbuZbvBeABWF.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/myUser/.Bytecode-Viewer/bcv_temp/yOFBVttFREvW/1.apk
I: Regular manifest package...
I: Decoding file-resources...
Successfully extracted Krakatau
Extracting Enjarify
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
Successfully extracted Enjarify
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Exception in thread "Import Resource" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1750)
	at java.util.HashMap.putVal(HashMap.java:642)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at com.googlecode.dex2jar.ir.ts.UniqueQueue.add(UniqueQueue.java:31)
	at com.googlecode.dex2jar.ir.ts.UniqueQueue.addAll(UniqueQueue.java:21)
	at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.markUsed(UnSSATransformer.java:401)
	at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.analyzeValue(UnSSATransformer.java:374)
	at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:57)
	at com.googlecode.dex2jar.ir.ts.UnSSATransformer.transform(UnSSATransformer.java:274)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:132)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:598)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:24)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:91)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:782)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:549)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:450)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:606)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:146)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:246)
	at the.bytecode.club.bytecodeviewer.util.Dex2Jar.dex2Jar(Dex2Jar.java:42)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.APKResourceImporter.open(APKResourceImporter.java:66)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:87)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:59)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ThexXTURBOXx** [comment]
Sorry for the late reply. Have you tried assigning more RAM to BCV?
