### ISSUE TITLE
This happens if I open a folder and  click on a class file down the folder hierarchy

### ISSUE THREAD

**Issue by mhupfer** [Konloch/bytecode-viewer#455]
Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytecode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.11.2 [Fat Jar], OS: Linux, Java: 11.0.16

java.lang.IllegalStateException: LabelNode index not found. (Label not in InsnList?)
	at the.bytecode.club.bytecodeviewer.decompilers.bytecode.InstructionPrinter.resolveLabel(InstructionPrinter.java:384)
	at the.bytecode.club.bytecodeviewer.decompilers.bytecode.MethodNodeDecompiler.decompile(MethodNodeDecompiler.java:156)
	at the.bytecode.club.bytecodeviewer.decompilers.bytecode.ClassNodeDecompiler.decompile(ClassNodeDecompiler.java:95)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.BytecodeDisassembler.decompileClassNode(BytecodeDisassembler.java:35)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:108)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:159)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Konloch** [comment]
This should be fixed in the next update. To test this version out you can use latest release snapshot - https://github.com/Konloch/bytecode-viewer/actions/runs/11136072303

If anyone encounters this issue with the latest update, just open a new issue.
