### ISSUE TITLE
ava.lang.IllegalArgumentException: Self-suppression not permitted

### ISSUE THREAD

**Issue by kero1998a** [Konloch/bytecode-viewer#469]
Please send this error log to https://github.com/Konloch/bytecode-viewer/issues or Konloch at https://the.bytecode.club or konloch@gmail.com
If you hold appropriate legal rights to the relevant class/jar/apk file please include that as well.
Bytecode Viewer Version: 2.11.2 [Fat Jar], OS: Windows 11, Java: 1.8.0_361

java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.lang.Throwable.addSuppressed(Unknown Source)
	at the.bytecode.club.bytecodeviewer.resources.ResourceContainerImporter.importAsZip(ResourceContainerImporter.java:85)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.ZipResourceImporter.open(ZipResourceImporter.java:41)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:87)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:59)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
[README.md](https://github.com/Konloch/bytecode-viewer/files/10848882/README.md)

**Comment by Konloch** [comment]
To fix this you'll need to allocate more memory via ``java -Xmx3G -jar BCV.jar``

You may need to play around with the `3G` value to find the correct amount
