### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by L-pin** [Konloch/bytecode-viewer#489]
Hello,

I encountered the following error while decompiling a class using bytecode-viewer. Since the class file is not convenient to publicly share, I have emailed it to you. I hope to receive your reply. Thank you.

```
java.lang.ArrayIndexOutOfBoundsException: Index 65350 out of bounds for length 113
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2441)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1515)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:745)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
	at the.bytecode.club.bytecodeviewer.api.ASMUtil.bytesToNode(ASMUtil.java:42)
	at the.bytecode.club.bytecodeviewer.util.JarUtils.getNode(JarUtils.java:242)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.ClassResourceImporter.open(ClassResourceImporter.java:47)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:87)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:59)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
![image](https://github.com/Konloch/bytecode-viewer/assets/23657203/43e373fd-6733-43e0-9580-d854f9011c77)

**Comment by Akhilmak** [comment]
Hey @Konloch can I work on this issue if it is still open?

**Comment by Konloch** [comment]
@Akhilmak are you also running into this issue? If you have a reproducible build you can share that causes this bug, that would help out.

If you want feel free to join our Discord - https://discord.gg/aexsYpfMEf and just ping me there, we could try to resolve this issue
