### ISSUE TITLE
Not a valid dex magic value

### ISSUE THREAD

**Issue by Syed-Bipul-Rahman** [Konloch/bytecode-viewer#512]
Hi, 
I have got this issue _when I try to decompile apk using **MacOs**_

```
com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd
	at com.android.tools.smali.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:92)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:172)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:199)
	at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:180)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:88)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:36)
	at brut.androlib.ApkDecoder.decodeSourcesSmali(ApkDecoder.java:220)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:143)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
	at the.bytecode.club.bytecodeviewer.util.APKTool.decodeResources(APKTool.java:41)
	at the.bytecode.club.bytecodeviewer.resources.importing.impl.APKResourceImporter.open(APKResourceImporter.java:55)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.importKnownFile(ImportResource.java:87)
	at the.bytecode.club.bytecodeviewer.resources.importing.ImportResource.run(ImportResource.java:59)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by Konloch** [comment]
Hi, if you hold appropriate legal rights to the file that causes this exception, could you please send it to [konloch@gmail.com](mailto:konloch@gmail.com) so I can investigate this?

**Comment by ThexXTURBOXx** [comment]
This is only a guess, but I just think, the APK might be broken or is in some unknown format: https://source.android.com/docs/core/runtime/dex-format#dex-file-magic
