### ISSUE TITLE
Got StringIndexOutOfBoundsException stacktrace while saving decompiled as Java files

### ISSUE THREAD

**Issue by rshmelev** [Konloch/bytecode-viewer#52]
Hi! :) 

Bytecode Viewer Version: 2.9.5

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1955)
	at com.strobel.assembler.metadata.CoreMetadataFactory.makeNamedType(CoreMetadataFactory.java:229)
	at com.strobel.assembler.metadata.signatures.Reifier.visitClassTypeSignature(Reifier.java:109)
	at com.strobel.assembler.metadata.signatures.ClassTypeSignature.accept(ClassTypeSignature.java:46)
	at com.strobel.assembler.metadata.MetadataParser.parseTypeSignature(MetadataParser.java:123)
	at com.strobel.assembler.metadata.MetadataParser.parseTypeDescriptor(MetadataParser.java:114)
	at com.strobel.assembler.metadata.ClassFileReader.populateAnonymousInnerTypes(ClassFileReader.java:763)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:443)
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:366)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at the.bytecode.club.bytecodeviewer.decompilers.ProcyonDecompiler.doSaveJarDecompiled(ProcyonDecompiler.java:207)
	at the.bytecode.club.bytecodeviewer.decompilers.ProcyonDecompiler.decompileToZip(ProcyonDecompiler.java:166)
	at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI$11$1.run(MainViewerGUI.java:829)

**Comment by Konloch** [comment]
This is an issue with proycon, select another decompiler, that should solve the issue.

Thanks for the bug report however!
