### ISSUE TITLE
Selected incorrect file for Krakatau

### ISSUE THREAD

**Issue by EriX24** [Konloch/bytecode-viewer#524]
I selected "C:/" instead of the correct file, is there a way to reverse this? (I'm on Windows as well)

```
java.io.IOException: Cannot run program "C:\": CreateProcess error=5, Access is denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at the.bytecode.club.bytecodeviewer.decompilers.impl.KrakatauDecompiler.decompileClassNode(KrakatauDecompiler.java:202)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:108)
	at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:159)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.io.IOException: CreateProcess error=5, Access is denied
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 5 more
```

**Comment by Konloch** [comment]
Hi, using `Settings>Set Python` should allow you to resolve the incorrect path.

![image](https://github.com/user-attachments/assets/f7946602-be23-4529-8048-35badea2a162)

**Comment by EriX24** [comment]
Thanks!

**Comment by EriX24** [comment]
Wait, If I don't have 2.7 is there another way to run it?

**Comment by EriX24** [comment]
I used set 3.X, but it seems to have no effect

**Comment by Konloch** [comment]
Hi, Python 3.X is for Enjarify, Krakatau requires 2.X via Python or PyPy.

**Comment by EriX24** [comment]
oh, ok

**Comment by EriX24** [comment]
it worked

**Comment by Janmm14** [comment]
(pypy is preferred for krakatau, it runs way faster)
